// ==============================================================================
// FIREBASE INITIALIZATION SERVICE
// ==============================================================================
// Handles Firebase initialization using auto-generated configuration
// Generated by: flutterfire configure --project=stakeholder-management-367ba
// ==============================================================================

import 'package:firebase_core/firebase_core.dart';
import '../firebase_options.dart';

class FirebaseService {
  static Future<void> initialize() async {
    // Initialize Firebase with auto-generated options
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }
}
