import '../models/models.dart';

class MockDataService {
  static List<EventModel> getMockEvents(String userId) {
    final now = DateTime.now();
    return [
      EventModel(
        id: 'event_1',
        title: 'Team Sprint Planning',
        description: 'Q1 2026 sprint planning session with engineering team',
        startTime: now.add(const Duration(days: 1, hours: 9)),
        endTime: now.add(const Duration(days: 1, hours: 11)),
        location: const EventLocation(
          name: 'Conference Room A',
          address: '123 Main St, Suite 400',
          isVirtual: false,
        ),
        status: EventStatus.scheduled,
        priority: EventPriority.high,
        ownerId: userId,
        stakeholderIds: ['stakeholder_1', 'stakeholder_2'],
        createdAt: now.subtract(const Duration(days: 2)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      EventModel(
        id: 'event_2',
        title: 'Client Demo',
        description: 'Product demonstration for new client - Project Phoenix',
        startTime: now.add(const Duration(days: 3, hours: 14)),
        endTime: now.add(const Duration(days: 3, hours: 15)),
        location: const EventLocation(
          name: 'Virtual Meeting',
          virtualLink: 'https://zoom.us/j/1234567890',
          isVirtual: true,
        ),
        status: EventStatus.scheduled,
        priority: EventPriority.urgent,
        ownerId: userId,
        stakeholderIds: ['stakeholder_3', 'stakeholder_2'],
        createdAt: now.subtract(const Duration(days: 3)),
        updatedAt: now.subtract(const Duration(hours: 5)),
      ),
      EventModel(
        id: 'event_3',
        title: 'Code Review Session',
        description: 'Weekly code review and feedback for backend services',
        startTime: now.add(const Duration(days: 5, hours: 10)),
        endTime: now.add(const Duration(days: 5, hours: 11)),
        location: const EventLocation(
          name: 'Google Meet',
          virtualLink: 'https://meet.google.com/abc-defg-hij',
          isVirtual: true,
        ),
        status: EventStatus.scheduled,
        priority: EventPriority.medium,
        ownerId: userId,
        stakeholderIds: ['stakeholder_1', 'stakeholder_4'],
        createdAt: now.subtract(const Duration(days: 5)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      EventModel(
        id: 'event_4',
        title: 'Project Kickoff',
        description: 'Kickoff meeting for new feature development',
        startTime: now.add(const Duration(hours: 2)),
        endTime: now.add(const Duration(hours: 3)),
        location: const EventLocation(
          name: 'Main Office',
          address: '123 Main St',
          isVirtual: false,
        ),
        status: EventStatus.inProgress,
        priority: EventPriority.high,
        ownerId: userId,
        stakeholderIds: ['stakeholder_1', 'stakeholder_2', 'stakeholder_4'],
        createdAt: now.subtract(const Duration(days: 1)),
        updatedAt: now,
      ),
      EventModel(
        id: 'event_5',
        title: 'Q4 Retrospective',
        description: 'Team retrospective for Q4 2025',
        startTime: now.subtract(const Duration(days: 30)),
        endTime: now.subtract(const Duration(days: 30, hours: -2)),
        location: const EventLocation(
          name: 'Conference Room B',
          address: '123 Main St, Suite 402',
          isVirtual: false,
        ),
        status: EventStatus.completed,
        priority: EventPriority.medium,
        ownerId: userId,
        stakeholderIds: ['stakeholder_1', 'stakeholder_2', 'stakeholder_4'],
        createdAt: now.subtract(const Duration(days: 35)),
        updatedAt: now.subtract(const Duration(days: 30)),
      ),
    ];
  }
  
  static List<StakeholderModel> getMockStakeholders() {
    final now = DateTime.now();
    return [
      StakeholderModel(
        id: 'stakeholder_1',
        name: 'Sarah Johnson',
        email: 'sarah.j@company.com',
        phone: '+1 (555) 123-4567',
        type: StakeholderType.internal,
        organization: 'Tech Corp',
        title: 'Team Lead',
        relationshipType: RelationshipType.organizer,
        participationStatus: ParticipationStatus.accepted,
        eventIds: ['event_1', 'event_3'],
        createdAt: now.subtract(const Duration(days: 90)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      StakeholderModel(
        id: 'stakeholder_2',
        name: 'Michael Chen',
        email: 'michael.chen@company.com',
        phone: '+1 (555) 234-5678',
        type: StakeholderType.internal,
        organization: 'Tech Corp',
        title: 'Product Manager',
        relationshipType: RelationshipType.attendee,
        participationStatus: ParticipationStatus.accepted,
        eventIds: ['event_1', 'event_2'],
        createdAt: now.subtract(const Duration(days: 120)),
        updatedAt: now.subtract(const Duration(days: 2)),
      ),
      StakeholderModel(
        id: 'stakeholder_3',
        name: 'Jennifer Williams',
        email: 'j.williams@client.com',
        phone: '+1 (555) 345-6789',
        type: StakeholderType.external,
        organization: 'Acme Corp',
        title: 'CEO',
        relationshipType: RelationshipType.attendee,
        participationStatus: ParticipationStatus.tentative,
        eventIds: ['event_2'],
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      StakeholderModel(
        id: 'stakeholder_4',
        name: 'David Martinez',
        email: 'david.m@company.com',
        phone: '+1 (555) 456-7890',
        type: StakeholderType.internal,
        organization: 'Tech Corp',
        title: 'Senior Developer',
        relationshipType: RelationshipType.attendee,
        participationStatus: ParticipationStatus.accepted,
        eventIds: ['event_3', 'event_4'],
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      StakeholderModel(
        id: 'stakeholder_5',
        name: 'Emily Brown',
        email: 'emily.brown@vendor.com',
        phone: '+1 (555) 567-8901',
        type: StakeholderType.vendor,
        organization: 'Cloud Services Inc',
        title: 'Technical Account Manager',
        relationshipType: RelationshipType.attendee,
        participationStatus: ParticipationStatus.pending,
        eventIds: [],
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 7)),
      ),
      StakeholderModel(
        id: 'stakeholder_6',
        name: 'Robert Taylor',
        email: 'robert.t@company.com',
        phone: '+1 (555) 678-9012',
        type: StakeholderType.internal,
        organization: 'Tech Corp',
        title: 'UX Designer',
        relationshipType: RelationshipType.attendee,
        participationStatus: ParticipationStatus.declined,
        eventIds: [],
        createdAt: now.subtract(const Duration(days: 75)),
        updatedAt: now.subtract(const Duration(hours: 12)),
      ),
    ];
  }
}
