// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTfb7pev6wkDsdu-z2wAyFc7uakRy5or4',
    appId: '1:144390773762:web:db2c03f3524a79151e5b1b',
    messagingSenderId: '144390773762',
    projectId: 'stakeholder-management-367ba',
    authDomain: 'stakeholder-management-367ba.firebaseapp.com',
    storageBucket: 'stakeholder-management-367ba.firebasestorage.app',
    measurementId: 'G-27ZK04VYK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtHP3vh55MqiIDRfHk6dpHqAbDJbsCog',
    appId: '1:144390773762:android:8b6a327dc3dd82971e5b1b',
    messagingSenderId: '144390773762',
    projectId: 'stakeholder-management-367ba',
    storageBucket: 'stakeholder-management-367ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFlI7yRSQFjZU0QO4CIqdk2jNVeeWeZN8',
    appId: '1:144390773762:ios:3ddebb5cd27cfc231e5b1b',
    messagingSenderId: '144390773762',
    projectId: 'stakeholder-management-367ba',
    storageBucket: 'stakeholder-management-367ba.firebasestorage.app',
    iosBundleId: 'com.example.schedulingAndStakeholderManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFlI7yRSQFjZU0QO4CIqdk2jNVeeWeZN8',
    appId: '1:144390773762:ios:3ddebb5cd27cfc231e5b1b',
    messagingSenderId: '144390773762',
    projectId: 'stakeholder-management-367ba',
    storageBucket: 'stakeholder-management-367ba.firebasestorage.app',
    iosBundleId: 'com.example.schedulingAndStakeholderManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTfb7pev6wkDsdu-z2wAyFc7uakRy5or4',
    appId: '1:144390773762:web:2142e037df04c9561e5b1b',
    messagingSenderId: '144390773762',
    projectId: 'stakeholder-management-367ba',
    authDomain: 'stakeholder-management-367ba.firebaseapp.com',
    storageBucket: 'stakeholder-management-367ba.firebasestorage.app',
    measurementId: 'G-D6N2TKN79M',
  );
}
