// ignore_for_file: deprecated_member_use

import 'package:flutter/material.dart';
import '../../models/models.dart';
import '../../services/services.dart';

class StakeholderCreateScreen extends StatefulWidget {
  const StakeholderCreateScreen({super.key});

  @override
  State<StakeholderCreateScreen> createState() => _StakeholderCreateScreenState();
}

class _StakeholderCreateScreenState extends State<StakeholderCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _stakeholderService = StakeholderService();
  
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _organizationController = TextEditingController();
  final _notesController = TextEditingController();
  
  StakeholderType _selectedType = StakeholderType.client;
  RelationshipType _selectedRelationship = RelationshipType.attendee;
  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _organizationController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _createStakeholder() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final now = DateTime.now();
      final stakeholder = StakeholderModel(
        id: '', // Will be generated by service
        name: _nameController.text.trim(),
        email: _emailController.text.trim(),
        phone: _phoneController.text.trim().isEmpty ? null : _phoneController.text.trim(),
        organization: _organizationController.text.trim().isEmpty ? null : _organizationController.text.trim(),
        type: _selectedType,
        relationshipType: _selectedRelationship,
        participationStatus: ParticipationStatus.pending,
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
        eventIds: [],
        createdAt: now,
        updatedAt: now,
        inviteStatus: InviteStatus.notInvited,
      );

      await _stakeholderService.createStakeholder(stakeholder);

      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Stakeholder created successfully!'),
          backgroundColor: Colors.green,
        ),
      );

      Navigator.of(context).pop(true); // Return true to indicate success
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error creating stakeholder: $e'),
          backgroundColor: Colors.red,
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Add Stakeholder',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
        ),
        centerTitle: true,
        elevation: 0,
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Name field
              _buildTextField(
                controller: _nameController,
                label: 'Full Name',
                icon: Icons.person,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a name';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Email field
              _buildTextField(
                controller: _emailController,
                label: 'Email Address',
                icon: Icons.email,
                keyboardType: TextInputType.emailAddress,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter an email';
                  }
                  if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$').hasMatch(value)) {
                    return 'Please enter a valid email';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Phone field
              _buildTextField(
                controller: _phoneController,
                label: 'Phone Number (optional)',
                icon: Icons.phone,
                keyboardType: TextInputType.phone,
              ),
              const SizedBox(height: 16),

              // Organization field
              _buildTextField(
                controller: _organizationController,
                label: 'Organization (optional)',
                icon: Icons.business,
              ),
              const SizedBox(height: 16),

              // Stakeholder Type dropdown
              _buildTypeDropdown(),
              const SizedBox(height: 16),

              // Relationship Type dropdown
              _buildRelationshipDropdown(),
              const SizedBox(height: 16),

              // Notes field
              _buildTextField(
                controller: _notesController,
                label: 'Notes (optional)',
                icon: Icons.notes,
                maxLines: 3,
              ),
              const SizedBox(height: 32),

              // Create button
              ElevatedButton(
                onPressed: _isLoading ? null : _createStakeholder,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.black,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                child: _isLoading
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                        ),
                      )
                    : const Text(
                        'Create Stakeholder',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required IconData icon,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
    int maxLines = 1,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      validator: validator,
      maxLines: maxLines,
      decoration: InputDecoration(
        labelText: label,
        prefixIcon: Icon(icon, color: Colors.grey[600]),
        filled: true,
        fillColor: Colors.grey[100],
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Colors.black, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Colors.red),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ),
    );
  }

  Widget _buildTypeDropdown() {
    return DropdownButtonFormField<StakeholderType>(
      value: _selectedType,
      decoration: InputDecoration(
        labelText: 'Stakeholder Type',
        prefixIcon: Icon(Icons.category, color: Colors.grey[600]),
        filled: true,
        fillColor: Colors.grey[100],
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ),
      items: StakeholderType.values.map((type) {
        return DropdownMenuItem(
          value: type,
          child: Text(_getTypeLabel(type)),
        );
      }).toList(),
      onChanged: (value) {
        if (value != null) {
          setState(() => _selectedType = value);
        }
      },
    );
  }

  Widget _buildRelationshipDropdown() {
    return DropdownButtonFormField<RelationshipType>(
      value: _selectedRelationship,
      decoration: InputDecoration(
        labelText: 'Relationship Type',
        prefixIcon: Icon(Icons.handshake, color: Colors.grey[600]),
        filled: true,
        fillColor: Colors.grey[100],
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ),
      items: RelationshipType.values.map((type) {
        return DropdownMenuItem(
          value: type,
          child: Text(_getRelationshipLabel(type)),
        );
      }).toList(),
      onChanged: (value) {
        if (value != null) {
          setState(() => _selectedRelationship = value);
        }
      },
    );
  }

  String _getTypeLabel(StakeholderType type) {
    switch (type) {
      case StakeholderType.internal:
        return 'Internal';
      case StakeholderType.external:
        return 'External';
      case StakeholderType.client:
        return 'Client';
      case StakeholderType.vendor:
        return 'Vendor';
      case StakeholderType.partner:
        return 'Partner';
    }
  }

  String _getRelationshipLabel(RelationshipType type) {
    switch (type) {
      case RelationshipType.organizer:
        return 'Organizer';
      case RelationshipType.presenter:
        return 'Presenter';
      case RelationshipType.attendee:
        return 'Attendee';
      case RelationshipType.sponsor:
        return 'Sponsor';
      case RelationshipType.guest:
        return 'Guest';
      case RelationshipType.support:
        return 'Support';
    }
  }
}
